### ISSUE TITLE
Capital Letters

### ISSUE THREAD

**Issue by jcuenod** [zfletch/beta-code-js#8]
I'm not sure whether there is a real BETACODE standard but I'm working with files that have capitalised letters like: `*I)SRAH/L`

Right now It seems as though capitals can only be represented with diacritics as `*)ISRAH/L`. Is this intentional and correct?

**Comment by zfletch** [comment]
I'd like this library to work for as much real-world beta code as possible, regardless of whether it meets the standard. The code was originally designed and tested using sample beta code taken from the [Perseus Digital Library](http://www.perseus.tufts.edu/hopper/). It probably reflects that project's particular dialect.

In the texts you've been working on, have you found any other combinations of characters that are ordered differently from the way `beta-code-js` expects? If there are only a few cases, then I'll update the JSON. If there are a lot of cases, I might have to explore changing the algorithm.

**Comment by jcuenod** [comment]
In the files at [ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/](url) capital letters have accents after the vowel. This library appears to expect the accent characters to precede the vowel when it's capitalised.

**Comment by zfletch** [comment]
I've [updated](https://github.com/zfletch/beta-code-js/commit/3982ec72c2ab081647e370951c0d8db90564f859) the beta code conversion and pushed a new version ([1.0.8](https://www.npmjs.com/package/beta-code-js/v/1.0.8)) to npm. It should work with `*I)SRAH/L` now.

**Comment by jcuenod** [comment]
Awesome!
